### PR TITLE
Added support for s390x architecture which has a different cron.daily…

### PR DESCRIPTION
**Pull request by bschonec**

### CODE REVIEW

**Comment by robinbowes** [comment]
Thanks for this.

Can you fix the tests?

R.

**Comment by bschonec** [comment]
I would love to but I have absolutely no idea how to do so.  I've read and read the online docs but I have no experience writing them.  Also I have no access to anyone that can show me how.  I'll play around this weekend and try to learn.

**Comment by bastelfreak** [comment]
Hi @bschonec. We recently migrated this module to Vox Pupuli. Feel free to join our IRC channel #voxpupuli on freenode. We're always happy to help and guide you through testing.

**Comment by juniorsysadmin** [comment]
@bschonec This PR needs a rebase. Are you still interested in merging this?

**Comment by bastelfreak** [comment]
Hi, I'm going to close this PR due to inactivity. Please reopen and rebase it if you're still interested in it.

**Pull request closed without merging**
