### PR TITLE
Puppet 4 Types and remove puppet 3.x

### PR DESCRIPTION
**Pull request by cyberious**

### CODE REVIEW

**Comment by robinbowes** [comment]
Thanks for this.

I'm currently contemplating how to approach puppet 4 - I need to review Best Practise as recommended by puppet.

In the meantime, do you think you could look at why the tests are failing?

Many thanks,

R.

**Comment by bastelfreak** [comment]
Hi @cyberious, thank you so much for this amazing PR! We recently migrated this module to Vox Pupuli. I would love to merge your pull request, can you please rebase?

**Comment by cyberious** [comment]
After initial attempts it looks to be a beast of a rebase almost easier to completely rewrite what I did.

**Comment by wyardley** [comment]
Closing via #68

**Pull request closed without merging**
